### 1. 회원가입 요청 (Register)
# 설명: 초대코드(ABA2026)를 이용해 치료사 계정을 생성합니다.
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "therapist@test.com",
  "password": "password123!",
  "name": "김치료",
  "role": "THERAPIST",
  "inviteCode": "ABA2026"
}

### 2. 로그인 요청 (Login)
# 설명: 위에서 만든 계정으로 로그인하여 JWT 토큰을 받습니다.
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "therapist@test.com",
  "password": "password123!"
}

### 3. 관리자 회원가입 (Admin Register)
# 설명: role을 'ADMIN'으로 설정하여 관리자 계정을 생성합니다.
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "admin@aba.com",
  "password": "admin1234!",
  "name": "관리자",
  "role": "ADMIN",
  "inviteCode": "ABA2026"
}

### 4. 관리자 로그인 (Admin Login)
# 설명: 관리자 토큰을 발급받습니다. (아동 등록 시 필요)&& 응답에서 accessToken을 꺼내서 'auth_token'이라는 변수에 저장
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@aba.com",
  "password": "admin1234!"
}
> {%
    client.global.set("auth_token", response.body.data.accessToken);
%}

### 5. 아동 등록 (Create Child) - Admin Only
# ⚠️ 주의: Header에 '관리자 accessToekn 토큰'을 넣어야 합니다.
# ⚠️ 주의: "therapistId"에 위에서 조회한 UUID를 꼭 넣으세요!
POST http://localhost:8080/api/v1/children
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "김철수",
  "birthDate": "2020-05-05",
  "gender": "MALE",
  "diagnosis": "자폐 스펙트럼 장애 (ASD)",
  "currentDevLevel": "눈 맞춤이 어렵고 발화가 제한적임",
  "parentCharacteristics": "가정 연계 치료에 적극적임",
  "requestDetails": "이름 호명 반응 개선 희망",
  "therapistId": "3391df24-f382-4736-95b7-74f2ba73b09b"
}

### 6. 치료사 로그인 (Therapist Login)
# 설명: 다시 치료사로 로그인해서 내 담당 아동을 조회합니다.
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "therapist@test.com",
  "password": "password123!"
}
> {%
    client.global.set("auth_token", response.body.data.accessToken);
%}

### 7. 아동 목록 조회 (List Children)
# 설명: 치료사가 담당하는 아동 목록을 가져옵니다.
GET http://localhost:8080/api/v1/children
Authorization: Bearer {{auth_token}}

### 8. 목표 생성 (Create Goal)
# ⚠️ 주의: URL의 {childId} 자리에 위 목록 조회에서 나온 아동 ID를 넣으세요.
POST http://localhost:8080/api/v1/children/19f5f936-ee6c-4d5c-ab09-8b3770d76fac/goals
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "이름 호명 시 3초간 눈 맞춤",
  "category": "SOCIAL",
  "description": "치료사가 1m 거리에서 이름을 불렀을 때 눈을 마주침",
  "targetSuccessRate": 80,
  "consecutiveDays": 3,
  "promptPlan": "언어적 촉구(Verbal) -> 제스처(Gestural) -> 소거"
}

### 9. 목표 목록 조회 (List Goals)
GET http://localhost:8080/api/v1/children/19f5f936-ee6c-4d5c-ab09-8b3770d76fac/goals
Authorization: Bearer {{auth_token}}